#include "accessibility_settings.hpp"

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

namespace client::systems {

bool AccessibilitySettings::load(const std::filesystem::path& config_path) {
  std::ifstream file(config_path);
  if (!file.is_open()) {
    std::cout << "[accessibility] Config file not found, using defaults: " << config_path << std::endl;
    return false;
  }

  std::string line;
  while (std::getline(file, line)) {
    // Skip empty lines and comments
    if (line.empty() || line[0] == '#') {
      continue;
    }

    // Parse key=value
    auto pos = line.find('=');
    if (pos == std::string::npos) {
      continue;
    }

    std::string key = line.substr(0, pos);
    std::string value = line.substr(pos + 1);

    // Trim whitespace
    key.erase(0, key.find_first_not_of(" \t"));
    key.erase(key.find_last_not_of(" \t") + 1);
    value.erase(0, value.find_first_not_of(" \t"));
    value.erase(value.find_last_not_of(" \t") + 1);

    // Apply settings
    if (key == "high_contrast") {
      high_contrast_ = (value == "true" || value == "1");
    } else if (key == "font_scale_index") {
      std::size_t idx = 0;
      std::istringstream iss(value);
      if (iss >> idx) {
        set_font_scale_index(idx);
      }
    }
  }

  std::cout << "[accessibility] Loaded settings: contrast=" << high_contrast_ 
            << ", font_scale=" << font_scale() << std::endl;
  return true;
}

bool AccessibilitySettings::save(const std::filesystem::path& config_path) const {
  // Create directory if it doesn't exist
  auto parent = config_path.parent_path();
  if (!parent.empty() && !std::filesystem::exists(parent)) {
    std::filesystem::create_directories(parent);
  }

  std::ofstream file(config_path);
  if (!file.is_open()) {
    std::cerr << "[accessibility] Failed to save config to: " << config_path << std::endl;
    return false;
  }

  file << "# R-Type Client Accessibility Settings\n";
  file << "# This file is automatically generated\n\n";
  file << "high_contrast=" << (high_contrast_ ? "true" : "false") << "\n";
  file << "font_scale_index=" << font_scale_idx_ << "\n";
  file << "\n# Font scale values: 1.0 (normal), 1.25 (medium), 1.5 (large)\n";

  std::cout << "[accessibility] Saved settings to: " << config_path << std::endl;
  return true;
}

float AccessibilitySettings::font_scale() const {
  if (font_scale_idx_ < font_scale_count) {
    return font_scales[font_scale_idx_];
  }
  return font_scales[0];
}

void AccessibilitySettings::set_font_scale_index(std::size_t idx) {
  if (idx < font_scale_count) {
    font_scale_idx_ = idx;
  }
}

void AccessibilitySettings::cycle_font_scale() {
  font_scale_idx_ = (font_scale_idx_ + 1) % font_scale_count;
}

}  // namespace client::systems
